// These styles apply to every route in the application
import Footer from 'app/Footer';
import Navbar from 'app/Navbar';
import '@styles/globals.css'
import { Inter } from "next/font/google"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter =Inter({subsets:['latin']})

export default function RootLayout({
  // Layouts must accept a children prop.
  // This will be populated with nested layouts or pages
  children
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
